CREATE TABLE KHUVUC(
  IP CHAR (10) PRIMARY KEY,
  tenKhuvuc varchar(50) NOT NULL,
  tang int
);

CREATE TABLE PHONG(
  MP CHAR(3) PRIMARY KEY,
  TENPHONG VARCHAR(10) NOT NULL,
  SOMAY INT,
  IP CHAR(10) REFERENCES KHUVUC(IP)
);

CREATE TABLE LOAI(
  IDLOAI VARCHAR(4) PRIMARY KEY,
  TENLOAI VARCHAR(20)
);

CREATE TABLE MAY(
  IDMAY VARCHAR(5) PRIMARY KEY,
  TENMAY VARCHAR(10) NOT NULL,
  IP CHAR(10) REFERENCES KHUVUC(IP),
  AD CHAR(2) NOT NULL,
  IDLOAI VARCHAR(4) REFERENCES LOAI(IDLOAI),
  MP CHAR(3) REFERENCES PHONG(MP)
);

CREATE TABLE PHANMEM(
  IDPM VARCHAR(20) PRIMARY KEY,
  TENPM VARCHAR(20) NOT NULL,
  NGAYMUA DATE,
  VERSION NUMBER,
  IDLOAI VARCHAR(4) REFERENCES LOAI(IDLOAI),
  GIA INT
);

CREATE TABLE CAIDAT(
  ID CHAR(5) PRIMARY KEY,
  IDMAY VARCHAR(5) REFERENCES MAY(IDMAY),
  NGAYCAI DATE,
  IDPM VARCHAR(20) REFERENCES PHANMEM(IDPM) on delete set null
);
ALTER TABLE PHANMEM MODIFY VERSION CHAR(3);
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/YYYY'; /*CHANGE DATE FORMAT */
DROP TABLE CAIDAT;
ALTER TABLE ... MODIFY .. ..;
ALTER TABLE PHANMEM ADD  VERSION CHAR(3);
ALTER TABLE PHANMEM MODIFY NGAYMUA DATE DEFAULT SYSDATE;
INSERT INTO PHONG(IP) VALUES('130.120.80');
DELETE FROM PHANMEM;
INSERT INTO KHUVUC(IP, TENKHUVUC) VALUES('130.120.83', 'Brin tang 3');
UPDATE PHONG SET IP='130.120.83' WHERE MP='s23'; 
UPDATE KHUVUC SET TANG='3' WHERE IP='130.120.83';
UPDATE PHANMEM SET GIA=(GIA-GIA*(10/100)) WHERE IDLOAI='PCNT';
INSERT INTO LOAI(IDLOAI, TENLOAI) VALUES('NC', 'Network Computuer');
INSERT INTO MAY(IDMAY, TENMAY,IP,AD,IDLOAI, MP) VALUES('p12','Poste 12', '130.120.82', 02, 'PCWS', 's21');
SELECT SYSDATE FROM DUAL;
SELECT * FROM PHONG;
SELECT * FROM LOAI;
SELECT * FROM MAY;
SELECT * FROM CAIDAT;
SELECT * FROM PHANMEM;
/* 5*/
ALTER TABLE MAY ADD NBLOG SMALLINT;
ALTER TABLE PHANMEM ADD NBINSTALL SMALLINT;
UPDATE PHANMEM SET NBINSTALL=2 WHERE IDPM='log7';
UPDATE MAY SET NBLOG=1 WHERE IDMAY='p12';
/*6*/
CREATE TABLE PHANMEMUNIX(
  IDPM VARCHAR(20) PRIMARY KEY,
  TENPM VARCHAR(20) NOT NULL,
  NGAYMUA DATE,
  VERSION CHAR(3)
);
/*8*/
ALTER TABLE PHANMEMUNIX ADD GIA INT;
/*9*/
ALTER TABLE PHANMEMUNIX MODIFY VERSION CHAR(15);
/*10*/
ALTER TABLE PHANMEMUNIX MODIFY TENPM VARCHAR(20) UNIQUE; 
/*11*/
INSERT INTO PHANMEMUNIX(IDPM, TENPM, NGAYMUA, VERSION, GIA) SELECT  IDPM, TENPM, NGAYMUA, VERSION,GIA FROM PHANMEM; /*COPY DATA FROM ANOTHER TABLE*/
/*12*/
ALTER TABLE PHANMEMUNIX DROP COLUMN VERSION;
/**/
SELECT * FROM PHANMEMUNIX;
SELECT * FROM PHANMEM;
/*13*/
DELETE FROM PHANMEM WHERE GIA>5000;
/*14*/
DELETE FROM PHANMEMUNIX WHERE GIA>5000;
/*15*/



